### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by davisbug** [samarthgowda96/resale_app#1]
To enable us to find dependencies while creating virtual environments for the project can you please add **requirements.txt**

**Comment by samarthgowda96** [comment]
Hi @cellscripts , Thanks for reminding, I have pushed the file and also I'm planning to release part -2 of this application, But that said, I hope you find this small application interesting, Please feel free to open issues, if any, Thanks, Sam :)

**Comment by davisbug** [comment]
Yeah, it's an interesting application and keep up the good work @samarthgowda96
